"""remove location connection tables

Revision ID: 4147b1fd9292
Revises: d317977dfd8e
Create Date: 2025-05-02 17:27:25.238336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4147b1fd9292'
down_revision: Union[str, None] = 'd317977dfd8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_character_association')
    op.drop_table('location_connections')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_connections',
    sa.Column('from_location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], name='location_connections_from_location_id_fkey'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], name='location_connections_to_location_id_fkey'),
    sa.PrimaryKeyConstraint('from_location_id', 'to_location_id', name='location_connections_pkey')
    )
    op.create_table('location_character_association',
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='location_character_association_character_id_fkey'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='location_character_association_location_id_fkey'),
    sa.PrimaryKeyConstraint('location_id', 'character_id', name='location_character_association_pkey')
    )
    # ### end Alembic commands ###
