"""Add brief_description to Story model

Revision ID: 85c68725b8e0
Revises: bfd70e4f42a5
Create Date: 2025-05-08 17:13:10.774641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c68725b8e0'
down_revision: Union[str, None] = 'bfd70e4f42a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('brief_description', sa.Text(), nullable=True))
    op.alter_column('stories', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stories', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stories', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('stories', 'rules',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.create_unique_constraint(None, 'stories', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stories', type_='unique')
    op.alter_column('stories', 'rules',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stories', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stories', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stories', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('stories', 'brief_description')
    # ### end Alembic commands ###
