"""message

Revision ID: 972c60f81652
Revises: cb0bcc5c65dd
Create Date: 2025-03-27 22:19:57.527593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972c60f81652'
down_revision: Union[str, None] = 'cb0bcc5c65dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_character_association',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('location_id', 'character_id')
    )
    op.create_table('location_connections',
    sa.Column('from_location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('from_location_id', 'to_location_id')
    )
    op.add_column('characters', sa.Column('personalityTraits', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('backstory', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('goals', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('speaking_style', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('relationships', sa.String(), nullable=True))
    op.alter_column('characters', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('characters', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('characters', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('characters', 'relationship_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('characters', 'details')
    op.add_column('stories', sa.Column('rules', sa.String(), nullable=True))
    op.alter_column('stories', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stories', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('stories', 'prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('stories', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stories', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('stories', 'rules')
    op.add_column('characters', sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('characters', 'relationship_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('characters', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('characters', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('characters', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('characters', 'relationships')
    op.drop_column('characters', 'speaking_style')
    op.drop_column('characters', 'goals')
    op.drop_column('characters', 'backstory')
    op.drop_column('characters', 'personality_traits')
    op.drop_table('location_connections')
    op.drop_table('location_character_association')
    # ### end Alembic commands ###
