"""rename prompt to description

Revision ID: a73074277fb3
Revises: 4147b1fd9292
Create Date: 2025-05-02 17:58:33.470143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a73074277fb3'
down_revision: Union[str, None] = '4147b1fd9292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the new column first, allowing NULL values temporarily
    op.add_column('scenes', sa.Column('description', sa.String(), nullable=True))
    
    # Copy data from prompt to description
    op.execute("UPDATE scenes SET description = prompt")
    
    # Make description NOT NULL
    op.alter_column('scenes', 'description', nullable=False)
    
    # Drop the old column
    op.drop_column('scenes', 'prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the old column back, allowing NULL temporarily
    op.add_column('scenes', sa.Column('prompt', sa.VARCHAR(), nullable=True))
    
    # Copy data from description to prompt
    op.execute("UPDATE scenes SET prompt = description")
    
    # Make prompt NOT NULL
    op.alter_column('scenes', 'prompt', nullable=False)
    
    # Drop the new column
    op.drop_column('scenes', 'description')
    # ### end Alembic commands ###
