"""add role to the message

Revision ID: c7375a4ba361
Revises: a73074277fb3
Create Date: 2025-05-02 19:43:15.793535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7375a4ba361'
down_revision: Union[str, None] = 'a73074277fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapter_character_association')
    op.drop_table('chapter_location_association')
    op.drop_index('ix_chapters_id', table_name='chapters')
    op.drop_index('ix_chapters_title', table_name='chapters')
    op.drop_table('chapters')
    op.add_column('messages', sa.Column('role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'role')
    op.create_table('chapters',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('chapters_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name='chapters_story_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chapters_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_chapters_title', 'chapters', ['title'], unique=False)
    op.create_index('ix_chapters_id', 'chapters', ['id'], unique=False)
    op.create_table('chapter_location_association',
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name='chapter_location_association_chapter_id_fkey'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='chapter_location_association_location_id_fkey'),
    sa.PrimaryKeyConstraint('chapter_id', 'location_id', name='chapter_location_association_pkey')
    )
    op.create_table('chapter_character_association',
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name='chapter_character_association_chapter_id_fkey'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='chapter_character_association_character_id_fkey'),
    sa.PrimaryKeyConstraint('chapter_id', 'character_id', name='chapter_character_association_pkey')
    )
    # ### end Alembic commands ###
