"""message

Revision ID: cb0bcc5c65dd
Revises: 226550a71de2
Create Date: 2025-03-23 17:59:57.912249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0bcc5c65dd'
down_revision: Union[str, None] = '226550a71de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('role', sa.String(), nullable=False))
    op.add_column('characters', sa.Column('details', sa.String(), nullable=False))
    op.add_column('characters', sa.Column('image_dir', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('image_prompt', sa.String(), nullable=True))
    op.drop_column('characters', 'prompt')
    op.drop_column('characters', 'avatar')
    op.add_column('locations', sa.Column('image_prompt', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('details', sa.String(), nullable=False))
    op.drop_column('locations', 'background')
    op.drop_column('locations', 'prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('locations', sa.Column('background', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('locations', 'details')
    op.drop_column('locations', 'image_prompt')
    op.add_column('characters', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('characters', 'image_prompt')
    op.drop_column('characters', 'image_dir')
    op.drop_column('characters', 'details')
    op.drop_column('characters', 'role')
    # ### end Alembic commands ###
