"""add_status_to_scene_model

Revision ID: ed406e43b542
Revises: c7375a4ba361
Create Date: 2025-05-05 20:43:39.168798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = 'ed406e43b542'
down_revision: Union[str, None] = 'c7375a4ba361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add the column as nullable first
    op.add_column('scenes', sa.Column('status', sa.String(), nullable=True))
    
    # Update existing records with the default value
    op.execute(text("UPDATE scenes SET status = 'generation_not_started'"))
    
    # Alter the column to be non-nullable
    op.alter_column('scenes', 'status', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'status')
    # ### end Alembic commands ###
