services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/src
      - /src/node_modules
    environment:
      - NODE_ENV=development
      - REACT_RUN_HOST=0.0.0.0
      - REACT_RUN_PORT=5173
      - VITE_BACKEND_URL=http://localhost:5000 