"""message

Revision ID: 1d5b3511f000
Revises: 07183f85dd2f
Create Date: 2025-04-03 22:51:16.772586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5b3511f000'
down_revision: Union[str, None] = '07183f85dd2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('personality_traits', sa.String(), nullable=True))
    op.drop_column('characters', 'personalityTraits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('personalityTraits', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('characters', 'personality_traits')
    # ### end Alembic commands ###
