"""message

Revision ID: 226550a71de2
Revises: 
Create Date: 2025-03-18 01:54:30.698006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '226550a71de2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('locations', 'background',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'background',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('characters', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
