"""message

Revision ID: 89054eb0006d
Revises: 972c60f81652
Create Date: 2025-03-27 22:45:43.158697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89054eb0006d'
down_revision: Union[str, None] = '972c60f81652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('rules', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('colors', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('image_dir', sa.String(), nullable=True))
    op.alter_column('locations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('locations', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('locations', 'details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('locations', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('locations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('locations', 'image_dir')
    op.drop_column('locations', 'colors')
    op.drop_column('locations', 'rules')
    # ### end Alembic commands ###
