"""message

Revision ID: af9cf6c6d046
Revises: 89054eb0006d
Create Date: 2025-03-27 23:36:59.103517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af9cf6c6d046'
down_revision: Union[str, None] = '89054eb0006d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('uuid', sa.String(), nullable=False))
    op.alter_column('chapters', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chapters', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_chapters_title', table_name='chapters')
    op.drop_column('chapters', 'prompt')
    op.add_column('characters', sa.Column('uuid', sa.String(), nullable=False))
    op.add_column('locations', sa.Column('uuid', sa.String(), nullable=False))
    op.add_column('messages', sa.Column('uuid', sa.String(), nullable=False))
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('scenes', sa.Column('uuid', sa.String(), nullable=False))
    op.add_column('stories', sa.Column('uuid', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'uuid')
    op.drop_column('scenes', 'uuid')
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('messages', 'uuid')
    op.drop_column('locations', 'uuid')
    op.drop_column('characters', 'uuid')
    op.add_column('chapters', sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_chapters_title', 'chapters', ['title'], unique=False)
    op.alter_column('chapters', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chapters', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('chapters', 'uuid')
    # ### end Alembic commands ###
